# Generated by Django 4.0.6 on 2022-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchID', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=35)),
                ('year', models.IntegerField()),
                ('variant', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('z', models.IntegerField()),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('u', models.IntegerField()),
            ],
        ),
    ]
