# Generated by Django 4.0.6 on 2022-09-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markcheck', '0006_remove_thresholddata_o_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholddata1',
            name='u',
        ),
        migrations.RemoveField(
            model_name='thresholddata1',
            name='z',
        ),
        migrations.RemoveField(
            model_name='thresholddata_o',
            name='u',
        ),
    ]
